name: PermissionGranted
main: ru.ulmc.plugins.permissionGranted.PermissionGranted
version: 0.2
depend: [Vault]
commands:
   levelup:
      description: Get Some permgroup
      usage: /<command> info [permGroup] | get permGroup | forget permGroup | list
      permission: PermissionGranted.basic
      permission-message: You don't have permission to get a permission