name: PermissionGranted
main: ru.ulmc.plugins.permissionGranted.PermissionGranted
version: 0.1
depend: [Vault]
commands:
   levelup:
      description: Get Some profession
      usage: /<command> list | get [permGroup] | forget [permGroup]
      permission: PermissionGranted.basic
      permission-message: You don't have permission to get a permission